### ISSUE TITLE
Escolha de frete, forma de pagamento e resumo da compra não carregam

### ISSUE THREAD

**Issue by wemt** [diegosouza/one_step_checkout_simplificado#22]
Olá Diego, tudo bem? 

Primeiramente parabéns pelo módulo!

Acabei de instalar o módulo e infelizmente alguns itens não carregam no checkout:

![image](https://cloud.githubusercontent.com/assets/8421128/6879202/56822a88-d4cd-11e4-98e8-dcb3aeba5172.png)

Alguma idéia de como resolver isso?

**Comment by wemt** [comment]
Diego,

acabei de verificar que na hora que carrega a página todas estas informações aparecem, mas depois de um segundo elas somem e a tela fica como o print acima.

**Comment by diegosouza** [comment]
Não faço idéia do que pode ter acontecido, só inspecionando a instalação mesmo.
Atualmente não trabalho mais com e-commerce, então não pretendo evoluir esse projeto, que nasceu primeiramente p/ atender uma necessidade específica.

Fique à vontade para fazer fork e contratar alguém para esclarecer esse e demais problemas.

**Comment by wemt** [comment]
Ok Diego, muito obrigado mesmo assim.
